//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRPushUpgrade
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WRPushUpgrade.IWcfPushUpgrade")]
    public interface IWcfPushUpgrade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfPushUpgrade/TransportInterface", ReplyAction="http://tempuri.org/IWcfPushUpgrade/TransportInterfaceResponse")]
        byte[] TransportInterface(int enum_, byte[] input, Framework.IWcfPushUpgrade.EGZip_ gzip, Framework.IWcfPushUpgrade.EEncryption_ algorithm, Framework.IWcfPushUpgrade.ESerialisation_ formatIn, Framework.IWcfPushUpgrade.ESerialisation_ formatOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfPushUpgrade/TransportInterface", ReplyAction="http://tempuri.org/IWcfPushUpgrade/TransportInterfaceResponse")]
        System.Threading.Tasks.Task<byte[]> TransportInterfaceAsync(int enum_, byte[] input, Framework.IWcfPushUpgrade.EGZip_ gzip, Framework.IWcfPushUpgrade.EEncryption_ algorithm, Framework.IWcfPushUpgrade.ESerialisation_ formatIn, Framework.IWcfPushUpgrade.ESerialisation_ formatOut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IWcfPushUpgradeChannel : WRPushUpgrade.IWcfPushUpgrade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WcfPushUpgradeClient : System.ServiceModel.ClientBase<WRPushUpgrade.IWcfPushUpgrade>, WRPushUpgrade.IWcfPushUpgrade
    {
        
        public WcfPushUpgradeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public byte[] TransportInterface(int enum_, byte[] input, Framework.IWcfPushUpgrade.EGZip_ gzip, Framework.IWcfPushUpgrade.EEncryption_ algorithm, Framework.IWcfPushUpgrade.ESerialisation_ formatIn, Framework.IWcfPushUpgrade.ESerialisation_ formatOut)
        {
            return base.Channel.TransportInterface(enum_, input, gzip, algorithm, formatIn, formatOut);
        }
        
        public System.Threading.Tasks.Task<byte[]> TransportInterfaceAsync(int enum_, byte[] input, Framework.IWcfPushUpgrade.EGZip_ gzip, Framework.IWcfPushUpgrade.EEncryption_ algorithm, Framework.IWcfPushUpgrade.ESerialisation_ formatIn, Framework.IWcfPushUpgrade.ESerialisation_ formatOut)
        {
            return base.Channel.TransportInterfaceAsync(enum_, input, gzip, algorithm, formatIn, formatOut);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
