using System;
using System.Text;
using System.Data;
using System.Collections;
using System.Collections.Generic;

using Framework;

namespace SchemaDeploy
{
    //Table-Mapping Class (Customisable half)
    public partial class CValue
    {
        #region Constants
        #endregion

        #region Constructors (Public)
        //Default Connection String
        public CValue() : base() {}

        //Alternative Connection String
        public CValue(CDataSrc dataSrc) : base(dataSrc) {}
        
        //Hidden  (UI code should use cache instead)
        protected internal CValue(int valueClientId) : base(valueClientId) {}
        protected internal CValue(CDataSrc dataSrc, int valueClientId) : base(dataSrc, valueClientId) {}
        protected internal CValue(CDataSrc dataSrc, int valueClientId, IDbTransaction txOrNull) : base(dataSrc, valueClientId, txOrNull) { }
        #endregion

        #region Default Values
        protected override void InitValues_Custom()
        {
            //_sampleDateCreated = DateTime.Now;
            //_sampleSortOrder   = 0;
        }
        #endregion
        
        #region Default Connection String
        protected override CDataSrc DefaultDataSrc()  { return CDataSrc.Default;  }
        #endregion

        #region Properties - Relationships
        //Relationships - Foriegn Keys (e.g parent)
        public CKey Key { get { return CKey.Cache.GetById(this.ValueKeyName); } }
        public CInstance Instance { get { return CInstance.Cache.GetById(this.ValueInstanceId); } }

        //Relationships - Collections (e.g. children)
        #endregion

        #region Properties - Customisation
        public string GroupAndKey {  get { return Key.GroupAndKey; } }
        public string ValueAsString
        {
            get
            {
                switch (Key.KeyFormatId_)
                {
                    case EFormat.Boolean: return ValueBoolean.HasValue ? ValueBoolean.ToString() : string.Empty;
                    case EFormat.Integer: return ValueInteger.ToString();
                    case EFormat.String:  return ValueString ?? string.Empty;
                    default: throw new Exception("New Format: " + Key.KeyFormatId.ToString());
                }
            }
        }
        #endregion

        #region Save/Delete Overrides
        //Can Override base.Save/Delete (e.g. Cascade deletes, or insert related records)
        #endregion

        #region Custom Database Queries
        //(Not normally required for cached classes, use list class for searching etc)
        //For Stored Procs can use: MakeList (matching schema), or DataSrc.ExecuteDataset (reports etc)
        //For Dynamic sql, can use: SelectSum, SelectDistinct, SelectCount, SelectWhere (inherited methods)
        #endregion

        #region Searching (Optional)
        //For cached classes, custom seach logic resides in static methods on the list class
        // e.g. CValue.Cache.Search("...")

        //See also the auto-generated methods based on indexes
        //' e.g. CValue.Cache.GetBy...
        #endregion

        #region Caching Details
        //Cache Key
        internal static string CACHE_KEY = typeof(CValue).ToString();    //TABLE_NAME

        //Cache data
        private static CValueList LoadCache()  {   return new CValue().SelectAll();   }
        //Cache Timeout
        private static void SetCache(CValueList value)
        {
            if (null != value)  
                value.Sort(); 
            CCache.Set(CACHE_KEY, value);    //Optional parameter can override timeout (otherwise uses config-settings, which default to 3hrs)
        }
        //Helper Method
        private CValue CacheGetById(CValueList list)  { return list.GetById(this.ValueId);    }
        #endregion

        #region Cloning
        public CValue Clone(CDataSrc target, IDbTransaction txOrNull) //, int parentId)
        {
            //Shallow copy: Copies the immediate record, excluding autogenerated Pks
            CValue copy = new CValue(this, target);

            //Deep Copy - Child Entities: Cloned children must reference their cloned parent
            //copy.SampleParentId = parentId;

            copy.Save(txOrNull);

            //Deep Copy - Parent Entities: Cloned parents also clone their child collections
            //this.Children.Clone(target, txOrNull, copy.ValueClientId);

            return copy;
        }
        #endregion

        #region ToXml
        protected override void ToXml_Custom(System.Xml.XmlWriter w)
        {
            //Store(w, "Example", this.Example)
        }
        #endregion
    }
}