'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

Namespace WcfRefPassthru
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EGzip", [Namespace]:="http://schemas.datacontract.org/2004/07/Comms.Abstract")>  _
    Public Enum EGzip As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Input = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Output = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Both = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EEncryption", [Namespace]:="http://schemas.datacontract.org/2004/07/Comms.Abstract")>  _
    Public Enum EEncryption As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [Xor] = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Rij = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Xor_ = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ESerialisation", [Namespace]:="http://schemas.datacontract.org/2004/07/Comms.Abstract")>  _
    Public Enum ESerialisation As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Protobuf = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BinarySer = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WcfRefPassthru.IPassthru")>  _
    Public Interface IPassthru
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPassthru/TransportInterface", ReplyAction:="http://tempuri.org/IPassthru/TransportInterfaceResponse")>  _
        Function TransportInterface(ByVal enum_ As Integer, ByVal input() As Byte, ByVal gzip As WcfRefPassthru.EGzip, ByVal algorithm As WcfRefPassthru.EEncryption, ByVal formatIn As WcfRefPassthru.ESerialisation, ByVal formatOut As WcfRefPassthru.ESerialisation) As Byte()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPassthruChannel
        Inherits WcfRefPassthru.IPassthru, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PassthruClient
        Inherits System.ServiceModel.ClientBase(Of WcfRefPassthru.IPassthru)
        Implements WcfRefPassthru.IPassthru
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TransportInterface(ByVal enum_ As Integer, ByVal input() As Byte, ByVal gzip As WcfRefPassthru.EGzip, ByVal algorithm As WcfRefPassthru.EEncryption, ByVal formatIn As WcfRefPassthru.ESerialisation, ByVal formatOut As WcfRefPassthru.ESerialisation) As Byte() Implements WcfRefPassthru.IPassthru.TransportInterface
            Return MyBase.Channel.TransportInterface(enum_, input, gzip, algorithm, formatIn, formatOut)
        End Function
    End Class
End Namespace
