<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class FormOverwriteFiles
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(FormOverwriteFiles))
        Me.lblClassFiles = New System.Windows.Forms.Label
        Me.chkAutoGenerated = New System.Windows.Forms.CheckBox
        Me.chkCustomisable = New System.Windows.Forms.CheckBox
        Me.Label1 = New System.Windows.Forms.Label
        Me.chkSelectSingle = New System.Windows.Forms.CheckBox
        Me.chkSelectAll = New System.Windows.Forms.CheckBox
        Me.chkInsert = New System.Windows.Forms.CheckBox
        Me.chkUpdate = New System.Windows.Forms.CheckBox
        Me.chkDelete = New System.Windows.Forms.CheckBox
        Me.btnGenerate = New System.Windows.Forms.Button
        Me.btnCancel = New System.Windows.Forms.Button
        Me.SuspendLayout()
        '
        'lblClassFiles
        '
        Me.lblClassFiles.AutoSize = True
        Me.lblClassFiles.Location = New System.Drawing.Point(12, 9)
        Me.lblClassFiles.Name = "lblClassFiles"
        Me.lblClassFiles.Size = New System.Drawing.Size(157, 13)
        Me.lblClassFiles.TabIndex = 1
        Me.lblClassFiles.Text = "Partial-Class Files to Over-Write:"
        '
        'chkAutoGenerated
        '
        Me.chkAutoGenerated.AutoSize = True
        Me.chkAutoGenerated.Checked = True
        Me.chkAutoGenerated.CheckState = System.Windows.Forms.CheckState.Checked
        Me.chkAutoGenerated.Location = New System.Drawing.Point(28, 25)
        Me.chkAutoGenerated.Name = "chkAutoGenerated"
        Me.chkAutoGenerated.Size = New System.Drawing.Size(101, 17)
        Me.chkAutoGenerated.TabIndex = 2
        Me.chkAutoGenerated.Text = "Auto-Generated"
        Me.chkAutoGenerated.UseVisualStyleBackColor = True
        '
        'chkCustomisable
        '
        Me.chkCustomisable.AutoSize = True
        Me.chkCustomisable.Location = New System.Drawing.Point(28, 48)
        Me.chkCustomisable.Name = "chkCustomisable"
        Me.chkCustomisable.Size = New System.Drawing.Size(88, 17)
        Me.chkCustomisable.TabIndex = 3
        Me.chkCustomisable.Text = "Customisable"
        Me.chkCustomisable.UseVisualStyleBackColor = True
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Location = New System.Drawing.Point(12, 84)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(213, 13)
        Me.Label1.TabIndex = 4
        Me.Label1.Text = "Stored-Procedure Script Files to Over-Write:"
        '
        'chkSelectSingle
        '
        Me.chkSelectSingle.AutoSize = True
        Me.chkSelectSingle.Checked = True
        Me.chkSelectSingle.CheckState = System.Windows.Forms.CheckState.Checked
        Me.chkSelectSingle.Location = New System.Drawing.Point(28, 100)
        Me.chkSelectSingle.Name = "chkSelectSingle"
        Me.chkSelectSingle.Size = New System.Drawing.Size(88, 17)
        Me.chkSelectSingle.TabIndex = 5
        Me.chkSelectSingle.Text = "Select-Single"
        Me.chkSelectSingle.UseVisualStyleBackColor = True
        '
        'chkSelectAll
        '
        Me.chkSelectAll.AutoSize = True
        Me.chkSelectAll.Checked = True
        Me.chkSelectAll.CheckState = System.Windows.Forms.CheckState.Checked
        Me.chkSelectAll.Location = New System.Drawing.Point(28, 123)
        Me.chkSelectAll.Name = "chkSelectAll"
        Me.chkSelectAll.Size = New System.Drawing.Size(70, 17)
        Me.chkSelectAll.TabIndex = 6
        Me.chkSelectAll.Text = "Select-All"
        Me.chkSelectAll.UseVisualStyleBackColor = True
        '
        'chkInsert
        '
        Me.chkInsert.AutoSize = True
        Me.chkInsert.Checked = True
        Me.chkInsert.CheckState = System.Windows.Forms.CheckState.Checked
        Me.chkInsert.Location = New System.Drawing.Point(28, 146)
        Me.chkInsert.Name = "chkInsert"
        Me.chkInsert.Size = New System.Drawing.Size(52, 17)
        Me.chkInsert.TabIndex = 7
        Me.chkInsert.Text = "Insert"
        Me.chkInsert.UseVisualStyleBackColor = True
        '
        'chkUpdate
        '
        Me.chkUpdate.AutoSize = True
        Me.chkUpdate.Checked = True
        Me.chkUpdate.CheckState = System.Windows.Forms.CheckState.Checked
        Me.chkUpdate.Location = New System.Drawing.Point(28, 169)
        Me.chkUpdate.Name = "chkUpdate"
        Me.chkUpdate.Size = New System.Drawing.Size(61, 17)
        Me.chkUpdate.TabIndex = 8
        Me.chkUpdate.Text = "Update"
        Me.chkUpdate.UseVisualStyleBackColor = True
        '
        'chkDelete
        '
        Me.chkDelete.AutoSize = True
        Me.chkDelete.Location = New System.Drawing.Point(28, 192)
        Me.chkDelete.Name = "chkDelete"
        Me.chkDelete.Size = New System.Drawing.Size(218, 17)
        Me.chkDelete.TabIndex = 9
        Me.chkDelete.Text = "Delete (may have custom cascade logic)"
        Me.chkDelete.UseVisualStyleBackColor = True
        '
        'btnGenerate
        '
        Me.btnGenerate.DialogResult = System.Windows.Forms.DialogResult.OK
        Me.btnGenerate.Location = New System.Drawing.Point(15, 215)
        Me.btnGenerate.Name = "btnGenerate"
        Me.btnGenerate.Size = New System.Drawing.Size(137, 23)
        Me.btnGenerate.TabIndex = 10
        Me.btnGenerate.Text = "Generate Files"
        Me.btnGenerate.UseVisualStyleBackColor = True
        '
        'btnCancel
        '
        Me.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel
        Me.btnCancel.Location = New System.Drawing.Point(171, 215)
        Me.btnCancel.Name = "btnCancel"
        Me.btnCancel.Size = New System.Drawing.Size(75, 23)
        Me.btnCancel.TabIndex = 11
        Me.btnCancel.Text = "Cancel"
        Me.btnCancel.UseVisualStyleBackColor = True
        '
        'FormOverwriteFiles
        '
        Me.AcceptButton = Me.btnGenerate
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.CancelButton = Me.btnCancel
        Me.ClientSize = New System.Drawing.Size(256, 245)
        Me.Controls.Add(Me.btnCancel)
        Me.Controls.Add(Me.btnGenerate)
        Me.Controls.Add(Me.chkDelete)
        Me.Controls.Add(Me.chkUpdate)
        Me.Controls.Add(Me.chkInsert)
        Me.Controls.Add(Me.chkSelectAll)
        Me.Controls.Add(Me.chkSelectSingle)
        Me.Controls.Add(Me.Label1)
        Me.Controls.Add(Me.chkCustomisable)
        Me.Controls.Add(Me.chkAutoGenerated)
        Me.Controls.Add(Me.lblClassFiles)
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.Name = "FormOverwriteFiles"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent
        Me.Text = "Files to Over-Write"
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents lblClassFiles As System.Windows.Forms.Label
    Friend WithEvents chkAutoGenerated As System.Windows.Forms.CheckBox
    Friend WithEvents chkCustomisable As System.Windows.Forms.CheckBox
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents chkSelectSingle As System.Windows.Forms.CheckBox
    Friend WithEvents chkSelectAll As System.Windows.Forms.CheckBox
    Friend WithEvents chkInsert As System.Windows.Forms.CheckBox
    Friend WithEvents chkUpdate As System.Windows.Forms.CheckBox
    Friend WithEvents chkDelete As System.Windows.Forms.CheckBox
    Friend WithEvents btnGenerate As System.Windows.Forms.Button
    Friend WithEvents btnCancel As System.Windows.Forms.Button
End Class
