'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WRWcfDatasrc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WRWcfDatasrc.IWcfDataSrc")>  _
    Public Interface IWcfDataSrc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/ExecuteDataSet", ReplyAction:="http://tempuri.org/IWcfDataSrc/ExecuteDataSetResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ECmdType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CNameValue))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CNameValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CSelectWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCriteria)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ESign)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCriteria))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCommand))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of System.Data.DataSet))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Data.IsolationLevel))>  _
        Function ExecuteDataSet(ByVal cmd As Framework.CCommand) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/ExecuteNonQuery", ReplyAction:="http://tempuri.org/IWcfDataSrc/ExecuteNonQueryResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ECmdType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CNameValue))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CNameValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CSelectWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCriteria)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ESign)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCriteria))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCommand))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of System.Data.DataSet))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Data.IsolationLevel))>  _
        Function ExecuteNonQuery(ByVal cmd As Framework.CCommand) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/ExecuteScalar", ReplyAction:="http://tempuri.org/IWcfDataSrc/ExecuteScalarResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ECmdType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CNameValue))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CNameValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CSelectWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCriteria)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ESign)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCriteria))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCommand))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of System.Data.DataSet))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Data.IsolationLevel)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCommand))>  _
        Function ExecuteScalar(ByVal cmd As Framework.CCommand) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/Select", ReplyAction:="http://tempuri.org/IWcfDataSrc/SelectResponse")>  _
        Function [Select](ByVal where As Framework.CSelectWhere) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/SelectCount", ReplyAction:="http://tempuri.org/IWcfDataSrc/SelectCountResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CSelectWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCommand)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ECmdType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CNameValue))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CNameValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ESign)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCriteria))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCommand))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of System.Data.DataSet))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Data.IsolationLevel))>  _
        Function SelectCount(ByVal where As Framework.CWhere) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/Delete", ReplyAction:="http://tempuri.org/IWcfDataSrc/DeleteResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CSelectWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCommand)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ECmdType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CNameValue))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CNameValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ESign)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCriteria))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCommand))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of System.Data.DataSet))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Data.IsolationLevel))>  _
        Function Delete(ByVal where As Framework.CWhere) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/Insert", ReplyAction:="http://tempuri.org/IWcfDataSrc/InsertResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCommand)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ECmdType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CNameValue))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CNameValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CSelectWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCriteria)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ESign)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCriteria))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCommand))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of System.Data.DataSet))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Data.IsolationLevel))>  _
        Function Insert(ByVal tableName As String, ByVal pKeyName As String, ByVal insertPk As Boolean, ByVal data As System.Collections.Generic.List(Of Framework.CNameValue), ByVal oracleSequenceName As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/Update", ReplyAction:="http://tempuri.org/IWcfDataSrc/UpdateResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CSelectWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCommand)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ECmdType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CNameValue))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CNameValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ESign)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCriteria))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCommand))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of System.Data.DataSet))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Data.IsolationLevel))>  _
        Function Update(ByVal data As System.Collections.Generic.List(Of Framework.CNameValue), ByVal where As Framework.CWhere) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/UpdateOrdinals", ReplyAction:="http://tempuri.org/IWcfDataSrc/UpdateOrdinalsResponse")>  _
        Function UpdateOrdinals(ByVal tableName As String, ByVal pKeyName As String, ByVal ordinalName As String, ByVal data As System.Collections.Generic.List(Of Framework.CNameValue)) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/Paging", ReplyAction:="http://tempuri.org/IWcfDataSrc/PagingResponse")>  _
        Function Paging(ByRef count As Integer, ByVal pageIndexZeroBased As Integer, ByVal pageSize As Integer, ByVal tableName As String, ByVal descending As Boolean, ByVal sortByColumn As String, ByVal selectColumns As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/PagingWithFilters", ReplyAction:="http://tempuri.org/IWcfDataSrc/PagingWithFiltersResponse")>  _
        Function PagingWithFilters(ByRef count As Integer, ByVal pageIndexZeroBased As Integer, ByVal pageSize As Integer, ByVal tableName As String, ByVal descending As Boolean, ByVal sortByColumn As String, ByVal selectColumns As String, ByVal criteria As System.Collections.Generic.List(Of Framework.CCriteria)) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/BulkSelect", ReplyAction:="http://tempuri.org/IWcfDataSrc/BulkSelectResponse")>  _
        Function BulkSelect(ByVal tables As System.Collections.Generic.List(Of Framework.CCommand)) As System.Collections.Generic.List(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfDataSrc/BulkSaveDelete", ReplyAction:="http://tempuri.org/IWcfDataSrc/BulkSaveDeleteResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCommand)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ECmdType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CNameValue))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CNameValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CSelectWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CWhere)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.CCriteria)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Framework.ESign)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCriteria))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Framework.CCommand))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of System.Data.DataSet))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Data.IsolationLevel))>  _
        Sub BulkSaveDelete(ByVal saves As System.Collections.Generic.List(Of Object), ByVal deletes As System.Collections.Generic.List(Of Object), ByVal il As System.Data.IsolationLevel)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IWcfDataSrcChannel
        Inherits WRWcfDatasrc.IWcfDataSrc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class WcfDataSrcClient
        Inherits System.ServiceModel.ClientBase(Of WRWcfDatasrc.IWcfDataSrc)
        Implements WRWcfDatasrc.IWcfDataSrc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ExecuteDataSet(ByVal cmd As Framework.CCommand) As System.Data.DataSet Implements WRWcfDatasrc.IWcfDataSrc.ExecuteDataSet
            Return MyBase.Channel.ExecuteDataSet(cmd)
        End Function
        
        Public Function ExecuteNonQuery(ByVal cmd As Framework.CCommand) As Integer Implements WRWcfDatasrc.IWcfDataSrc.ExecuteNonQuery
            Return MyBase.Channel.ExecuteNonQuery(cmd)
        End Function
        
        Public Function ExecuteScalar(ByVal cmd As Framework.CCommand) As Object Implements WRWcfDatasrc.IWcfDataSrc.ExecuteScalar
            Return MyBase.Channel.ExecuteScalar(cmd)
        End Function
        
        Public Function [Select](ByVal where As Framework.CSelectWhere) As System.Data.DataSet Implements WRWcfDatasrc.IWcfDataSrc.[Select]
            Return MyBase.Channel.Select(where)
        End Function
        
        Public Function SelectCount(ByVal where As Framework.CWhere) As Integer Implements WRWcfDatasrc.IWcfDataSrc.SelectCount
            Return MyBase.Channel.SelectCount(where)
        End Function
        
        Public Function Delete(ByVal where As Framework.CWhere) As Integer Implements WRWcfDatasrc.IWcfDataSrc.Delete
            Return MyBase.Channel.Delete(where)
        End Function
        
        Public Function Insert(ByVal tableName As String, ByVal pKeyName As String, ByVal insertPk As Boolean, ByVal data As System.Collections.Generic.List(Of Framework.CNameValue), ByVal oracleSequenceName As String) As Object Implements WRWcfDatasrc.IWcfDataSrc.Insert
            Return MyBase.Channel.Insert(tableName, pKeyName, insertPk, data, oracleSequenceName)
        End Function
        
        Public Function Update(ByVal data As System.Collections.Generic.List(Of Framework.CNameValue), ByVal where As Framework.CWhere) As Integer Implements WRWcfDatasrc.IWcfDataSrc.Update
            Return MyBase.Channel.Update(data, where)
        End Function
        
        Public Function UpdateOrdinals(ByVal tableName As String, ByVal pKeyName As String, ByVal ordinalName As String, ByVal data As System.Collections.Generic.List(Of Framework.CNameValue)) As Integer Implements WRWcfDatasrc.IWcfDataSrc.UpdateOrdinals
            Return MyBase.Channel.UpdateOrdinals(tableName, pKeyName, ordinalName, data)
        End Function
        
        Public Function Paging(ByRef count As Integer, ByVal pageIndexZeroBased As Integer, ByVal pageSize As Integer, ByVal tableName As String, ByVal descending As Boolean, ByVal sortByColumn As String, ByVal selectColumns As String) As System.Data.DataSet Implements WRWcfDatasrc.IWcfDataSrc.Paging
            Return MyBase.Channel.Paging(count, pageIndexZeroBased, pageSize, tableName, descending, sortByColumn, selectColumns)
        End Function
        
        Public Function PagingWithFilters(ByRef count As Integer, ByVal pageIndexZeroBased As Integer, ByVal pageSize As Integer, ByVal tableName As String, ByVal descending As Boolean, ByVal sortByColumn As String, ByVal selectColumns As String, ByVal criteria As System.Collections.Generic.List(Of Framework.CCriteria)) As System.Data.DataSet Implements WRWcfDatasrc.IWcfDataSrc.PagingWithFilters
            Return MyBase.Channel.PagingWithFilters(count, pageIndexZeroBased, pageSize, tableName, descending, sortByColumn, selectColumns, criteria)
        End Function
        
        Public Function BulkSelect(ByVal tables As System.Collections.Generic.List(Of Framework.CCommand)) As System.Collections.Generic.List(Of System.Data.DataSet) Implements WRWcfDatasrc.IWcfDataSrc.BulkSelect
            Return MyBase.Channel.BulkSelect(tables)
        End Function
        
        Public Sub BulkSaveDelete(ByVal saves As System.Collections.Generic.List(Of Object), ByVal deletes As System.Collections.Generic.List(Of Object), ByVal il As System.Data.IsolationLevel) Implements WRWcfDatasrc.IWcfDataSrc.BulkSaveDelete
            MyBase.Channel.BulkSaveDelete(saves, deletes, il)
        End Sub
    End Class
End Namespace
