Public Class COverwriteFiles
    Public AutoGenerated As Boolean = True
    Public Customizable As Boolean = False

    Public SpSelectSingle As Boolean = True
    Public SpSelectAll As Boolean = True
    Public SpInsert As Boolean = True
    Public SpUpdate As Boolean = True
    Public SpDelete As Boolean = False
End Class
